# GitHub Pagesは直接リポジトリ構造からサービス
# 複雑なGitHub Actionsワークフローは無効化

name: Simple Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Repository structure info
        run: echo "GitHub Pages serves directly from main branch"